# Generated by Django 3.0.4 on 2020-04-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('precio', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField()),
                ('ingredientes', models.ManyToManyField(blank=True, to='burgerapp.Ingrediente')),
            ],
        ),
    ]
